trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'


jobs:
- job: CreateACR
  displayName: 'Create Azure Container Registry'
  steps:

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'ps'  # Use PowerShell Core (cross-platform) for Windows or Linux
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Variables
          $ACR_NAME='axwayTEST'       # Must be globally unique
          $RESOURCE_GROUP='RG-mavishnoi'
          $LOCATION='westus'         # e.g., eastus, westus, etc.

          # Create the Azure Container Registry
          Write-Host "Creating Azure Container Registry..."
          az acr create --name $ACR_NAME --resource-group $RESOURCE_GROUP --location $LOCATION --sku Basic --admin-enabled true

          Write-Host "Azure Container Registry $ACR_NAME created successfully!"